#!/usr/bin/env python3
import os
import shutil
from os.path import exists

toolbox = input("Toolbox name: ")
app = input("Application name: ")

filepath = f"/usr/share/applications/{app}.desktop"
print(f"Looking for {filepath}")

found = exists(filepath)
while not found:
    print(
        "File not found, please choose from the following (leave off the .desktop extension): \n"
    )
    print(os.listdir("/usr/share/applications"))

    app = input("Application name: ")
    filepath = f"/usr/share/applications/{app}.desktop"
    found = exists(filepath)

if found:
    print("File found!")
    home = os.path.expanduser("~")
    newpath = f"{home}/.local/share/applications/{app}.desktop"
    shutil.copyfile(filepath, newpath)
    print("File copied!")

    content = []
    with open(newpath, "r") as f:
        content = f.readlines()
        for idx, line in enumerate(content):
            if line.startswith("Exec="):
                print("found exec")
                content[idx] = line.replace("Exec=", f"Exec=toolbox run -c {toolbox} ")

    with open(newpath, "w") as f:
        f.writelines(content)
